language: objective-c
osx_image: xcode9
script: 
        - echo Install Cocoapods
        - gem install cocoapods -v  1.3.1

        - echo Install Example pod dependence
        - pushd Example
        - pod install --repo-update
        - popd

        - echo Build Example project 
        - xcodebuild -quiet -workspace Example/DemoApplication.xcworkspace -scheme DemoApplication -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO