language: objective-c
osx_image: xcode8
script: 
        - echo Install Cocoapods
        - gem install cocoapods -v  1.0.1
        - pod repo update


        - echo Install Demo pod dependence
        - pushd Demo
        - pod install
        - popd

        - echo Build Demo project
        - xcodebuild -workspace Demo/NIM.xcworkspace -scheme NIM -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO


        - echo Install Example pod dependence
        - pushd Example
        - pod install
        - popd

        - echo Build Example project 
        - xcodebuild -workspace Example/DemoApplication.xcworkspace -scheme DemoApplication -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO